---
# CAT 1 Fixes
#DISTRIBUTION STATEMENT A. Approved for public release. Distribution is unlimited.
#
#This material is based upon work supported by the Department of the Air Force and MISSILE DEFENSE AGENCY under Air Force Contract No. FA8702-15-D-0001. Any opinions, findings, conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the Department of the Air Force and MISSILE DEFENSE AGENCY.
#
#© 2023 Massachusetts Institute of Technology.
#
#The software/firmware is provided to you on an As-Is basis
#
#Delivered to the U.S. Government with Unlimited Rights, as defined in DFARS Part 252.227-7013 or 7014 (Feb 2014). Notwithstanding any copyright notice, U.S. Government rights in this work are defined by DFARS 252.227-7013 or DFARS 252.227-7014 as detailed above. Use of this work other than as specifically authorized by the U.S. Government may violate any copyrights that exist in this work.

# CAT 1 Fixes
- name: "HIGH | PGS9-00-000300 | Security-relevant software updates to PostgreSQL must be installed within the time period directed by an authoritative source (e.g., IAVM, CTOs, DTMs, and STIGs)."
  apt:
      name: "{{ pgs9stig_ubuntu_packages }}"
      state: latest
  when:
      - pgs9_00_000300
      - pgs9stig_cat1
  tags:
      - PGS9-00-000300
      - cat1

- name: |
      "HIGH | PGS9-00-008000 | PostgreSQL must implement NIST FIPS 140-2 validated cryptographic modules to generate and validate cryptographic hashes."
      "HIGH | PGS9-00-008200 | PostgreSQL must implement NIST FIPS 140-2 validated cryptographic modules to protect unclassified information requiring confidentiality and cryptographic protection, in accordance with the data owners requirements."
  command: /bin/true
  changed_when: false
  failed_when: false
  when:
      - pgs9_00_008000 or
        pgs9_00_008200
      - pgs9stig_cat1
  tags:
      - pgs9_00_008000
      - pgs9_00_008200
      -cat1

- name: "HIGH | PGS9-00-010200 | PostgreSQL must enforce authorized access to all PKI private keys stored/utilized by PostgreSQL."
  block:
      - name: "HIGH | PGS9-00-010200 | AUDIT | PostgreSQL must enforce authorized access to all PKI private keys stored/utilized by PostgreSQL."
        command: "true"
        register: pgs9_00_010200_audit
        check_mode: no
        changed_when: no
        with_items:
            - not implemented
      - name: "HIGH | PGS9-00-010200 | PATCH | PostgreSQL must enforce authorized access to all PKI private keys stored/utilized by PostgreSQL."
        command: "true"
        changed_when: no
        with_items:
            - not implemented
  when:
      - pgs9_00_010200
      - pgs9stig_cat1
  tags:
      - PGS9-00-010200
      - cat1
      - notimplemented

- name: "HIGH | PGS9-00-011700 | PostgreSQL must prevent non-privileged users from executing privileged functions, to include disabling, circumventing, or altering implemented security safeguards/countermeasures."
  block:
      - name: "HIGH | PGS9-00-011700 | AUDIT | PostgreSQL must prevent non-privileged users from executing privileged functions, to include disabling, circumventing, or altering implemented security safeguards/countermeasures."
        command: "true"
        register: pgs9_00_011700_audit
        check_mode: no
        changed_when: no
        with_items:
            - not implemented
      - name: "HIGH | PGS9-00-011700 | PATCH | PostgreSQL must prevent non-privileged users from executing privileged functions, to include disabling, circumventing, or altering implemented security safeguards/countermeasures."
        command: "true"
        changed_when: no
        with_items:
            - not implemented
  when:
      - pgs9_00_011700
      - pgs9stig_cat1
  tags:
      - PGS9-00-011700
      - cat1
      - notimplemented

- name: "HIGH | PGS9-00-012300 | PostgreSQL must use NIST FIPS 140-2 validated cryptographic modules for cryptographic operations."
  block:
      - name: "HIGH | PGS9-00-012300 | PATCH | PostgreSQL must use NIST FIPS 140-2 validated cryptographic modules for cryptographic operations."
        apt:
            name: openssl

      - name: "HIGH | PGS9-00-012300 | AUDIT | Check for FIPS validated version of openssl"
        shell: openssl version | grep 'fips'
        register: pgs9stig_openssl_fips_check
        failed_when: no
        changed_when: pgs9stig_openssl_fips_check.rc != 0

      - debug:
            msg: CAT 1 Finding non-FIPS validated version of openssl found
        changed_when: yes
        when: pgs9stig_openssl_fips_check is changed
  when:
      - pgs9_00_012300
      - cat1
      - pgs9stig_cat1
  tags:
      - PGS9-00-012300

- name: "HIGH | PGS9-00-012800 | The DBMS must be configured on a platform that has a NIST certified FIPS 140-2 installation of OpenSSL."
  debug:
      msg: CAT 1 Finding, non RHEL system
  changed_when: yes
  when:
      - pgs9_00_012800
      - ansible_distribution != "Ubuntu"
      - pgs9stig_cat1
  tags:
      - PGS9-00-012800
      - cat1

# CAT 2 Fixes


# CAT 3 Fixes
- name: "Currently no CAT3 STIG items for PGS9-STIG"
  debug:
      msg: "There are currently no CAT3 STIG items for PGS9-STIG"
  when:
      - pgs9stig_cat3
  tags:
      - cat3